<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ls</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>name</key>
	<string>LispyScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lispyscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lispyscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lispyscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lispyscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>constant.array.lispyscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>constant.object.lispyscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/[^\s]</string>
			<key>end</key>
			<string>/</string>
			<key>name</key>
			<string>string.regexp.lispyscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lispyscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.lispyscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:function|do|macro|loop|recur|if|cond|when|unless|var|set|include|try|throw|new|get|str)\s</string>
			<key>name</key>
			<string>keyword.control.lispyscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:true\?|false\?|undefined\?|null\?|zero\?|boolean\?|number\?|string\?|array\?|object\?)\s</string>
			<key>name</key>
			<string>keyword.operator.lispyscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:each|each2d|eachKey|map|reduce|assert|testGroup|testRunner|monad|doMonad|withMonad)\s</string>
			<key>name</key>
			<string>support.function.lispyscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:array|object|arrayInit|arrayInit2d|identityMonad|maybeMonad|arrayMonad|stateMonad|continuationMonad)\s</string>
			<key>name</key>
			<string>support.type.lispyscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lispyscript</string>
	<key>uuid</key>
	<string>86dcfa20-1c07-4a13-aa3d-f00b9ecab78d</string>
</dict>
</plist>
